#!/usr/bin/env zsh
# BETA

stadt=$(echo $1 | sed 's/ /%20/g')
strasse=$(echo $2 | sed 's/ /%20/g')
hausnummer=$(echo $3 | sed 's/ //g')

curl "http://www.postleitzahlen.de/postleitzahlen/index/search?method=searchSimple&city_id=&_dvform_posted=1&zipCity=${stadt}&street=${strasse}&streetNumber=${hausnummer}" -s | grep "\"poboxcodelist\"" -A16 | grep "<td>[0-9.]\{5\}<\/td>" | sed 's/.*\([0-9.]\{5\}\).*/\1/g'
