#!/usr/bin/env zsh

if [ "$1" = "" ]; then
	choice=$(echo "0: display-switch
1: keyboard-layout" | dmenu -b -nb '#222222' -nf '#888888' -sb '#285577' -sf '#ffffff' -p 'switch:')
else
	choice=$1
fi

case $choice in
	0*)
	echo "display-switch"
	${HOME}/bin/display-switch
	;;

	1*)
	echo "keyboard-layout"
	${HOME}/bin/keyboard-layout
	;;

	*)
	echo "invalid choice"
	exit 1
	;;
esac
